[package]
name = "Rotor-Dynamics-Model"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = { version = "0.29"}
serde = { version = "1.0", features = ["derive"] } # Needed for #[derive(Deserialize)]